# Generated by Django 4.1.7 on 2023-03-21 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KISILER',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('AD', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TAKI_TURU',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('AD', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GELEN_TAKILAR',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('AD', models.TextField(db_column='Ad')),
                ('SOYAD', models.TextField(blank=True, db_column='Soyad', null=True)),
                ('ACIKLAMA', models.TextField(blank=True, null=True)),
                ('MIKTAR', models.IntegerField(blank=True, null=True)),
                ('KISI', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sunnet.kisiler')),
                ('TAKI_TUR_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sunnet.taki_turu')),
            ],
        ),
    ]
