# Generated by Django 4.1.7 on 2023-03-22 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunnet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gelen_takilar',
            name='KISI',
        ),
        migrations.AddField(
            model_name='gelen_takilar',
            name='KISI_ID',
            field=models.ForeignKey(blank=True, db_column='KISI_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sunnet.kisiler'),
        ),
        migrations.AlterField(
            model_name='gelen_takilar',
            name='TAKI_TUR_ID',
            field=models.ForeignKey(blank=True, db_column='TAKI_TUR_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sunnet.taki_turu'),
        ),
    ]
