# Generated by Django 4.1.7 on 2023-03-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunnet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gelen_takilar',
            old_name='KISI_ID',
            new_name='KISI',
        ),
        migrations.RenameField(
            model_name='gelen_takilar',
            old_name='TAKI_TUR_ID',
            new_name='TAKI_TUR',
        ),
    ]
