# Generated by Django 4.1.7 on 2023-03-23 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunnet', '0003_alter_gelen_takilar_options_alter_kisiler_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gelen_takilar',
            name='KISI',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='sunnet.kisiler'),
        ),
    ]
