# Generated by Django 4.1.7 on 2023-03-24 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunnet', '0005_alter_gelen_takilar_kisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gelen_takilar',
            name='TAKI_TUR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sunnet.taki_turu'),
        ),
    ]
